import polars as pl

from ...... import rule
from ......domain.contracts import FixSafety
from ......facts import Enum
from ......query import FindingQuery, FixQuery, OccurrenceQuery, RuleQuery
from ......table import Table


@rule("PY-ENUM0001", fix_safety=FixSafety.SAFE)
def redundant_enum_value(subject: Table[Enum]) -> OccurrenceQuery:
    """Detect explicit enum values that standard `auto()` would preserve.

    Definition
    ----------
    Inspect direct subclasses of `Enum`, `IntEnum`, `StrEnum`, `Flag`, and `IntFlag`.
    A literal is redundant when it equals the next value generated by the standard
    enum implementation. Classes that override `_generate_next_value_` are excluded.
    String values in a plain `Enum` remain explicit because its `auto()` value is an
    increasing integer.

    Evidence
    --------
    Every finding identifies one assignment whose runtime value is preserved by `auto()`.

    Exceptions
    ----------
    Keep explicit protocol values, aliases, compatibility values, mixed value types,
    custom generation, and spelling whose public meaning differs from the member name.

    Examples
    --------
    `FAST = "fast"` in a `StrEnum`, `FIRST = 1` in an `Enum`, and `READ = 1` in
    a `Flag` are replaceable by `auto()`. `HTTP_OK = 200` and `PUBLIC = "public-name"`
    remain explicit.

    References
    ----------
    Cites "The Python Standard Library", enum documentation for `auto` and `_generate_next_value_`
    """
    relations = subject
    enums = (
        relations.records("enums")
        .filter(~pl.col("overrides_generate_next_value"))
        .select(
            "fact_id",
            pl.col("record_id").alias("enum_id"),
            pl.col("ordinal").alias("enum_ordinal"),
        )
    )
    members = relations.records("enums.members").select(
        "fact_order",
        "fact_id",
        "parent_id",
        "record_id",
        pl.col("ordinal").alias("member_ordinal"),
        "explicit_value_integer",
        "explicit_value_string",
        "standard_auto_value_integer",
        "standard_auto_value_string",
        "value_node.id",
        "value_node.span.path",
        "value_node.span.start_line",
        "value_node.span.start_column",
        "value_node.span.end_line",
        "value_node.span.end_column",
        "value_node.kind",
        "value_node.text",
    )
    selected = (
        members.join(
            enums,
            left_on=["fact_id", "parent_id"],
            right_on=["fact_id", "enum_id"],
            how="inner",
        )
        .filter(
            (
                pl.col("explicit_value_integer").is_not_null()
                & (pl.col("explicit_value_integer") == pl.col("standard_auto_value_integer"))
            )
            | (
                pl.col("explicit_value_string").is_not_null()
                & (pl.col("explicit_value_string") == pl.col("standard_auto_value_string"))
            )
        )
        .sort("fact_order", "enum_ordinal", "member_ordinal")
        .with_columns(
            (pl.col("record_id").cum_count().over("fact_id") - 1)
            .cast(pl.UInt64)
            .alias("rewrite_order")
        )
    )
    redundant = selected.select("fact_id").unique().with_columns(pl.lit(True).alias("value"))
    facts = (
        relations.facts()
        .join(redundant, on="fact_id", how="left")
        .with_columns(pl.col("value").fill_null(False))
    )
    rewritable = selected.filter(pl.col("value_node.id").is_not_null())
    rewrites = rewritable.select(
        "fact_id",
        "rewrite_order",
        pl.lit("replace").alias("kind"),
        pl.lit("auto()").alias("source"),
        pl.lit("").alias("placement"),
        pl.lit("").alias("name"),
        pl.lit("").alias("symbol_id"),
        pl.lit("").alias("symbol_name"),
        pl.lit(False).alias("references_complete"),
    )
    nodes = rewritable.select(
        "fact_id",
        "rewrite_order",
        pl.lit("target").alias("role"),
        pl.lit(0, dtype=pl.UInt64).alias("ordinal"),
        pl.col("value_node.id").alias("id"),
        pl.col("value_node.span.path").alias("path"),
        pl.col("value_node.span.start_line").alias("start_line"),
        pl.col("value_node.span.start_column").alias("start_column"),
        pl.col("value_node.span.end_line").alias("end_line"),
        pl.col("value_node.span.end_column").alias("end_column"),
        pl.col("value_node.kind").alias("kind"),
        pl.col("value_node.text").alias("text"),
    )
    imports = rewritable.select(
        "fact_id",
        "rewrite_order",
        pl.lit(0, dtype=pl.UInt64).alias("ordinal"),
        pl.lit("enum").alias("module"),
        pl.lit("auto").alias("name"),
        pl.lit("").alias("alias"),
        pl.lit(0, dtype=pl.UInt64).alias("level"),
        pl.lit(False).alias("type_only"),
    )
    return RuleQuery.boolean(
        facts,
        pl.col("value"),
        findings=FindingQuery.precise_boolean(
            facts,
            pl.col("value"),
            "redundant enum value",
            evidence=pl.col("evidence"),
        ),
        fix=FixQuery.build(
            "State each member whose value repeats the standard result as `auto()`.",
            rewrites=rewrites,
            nodes=nodes,
            imports=imports,
        ),
    )
