from collections.abc import Sequence
from pathlib import Path

from polars import DataFrame

class FunctionTables:
    @property
    def controls(self) -> DataFrame: ...
    @property
    def decorators(self) -> DataFrame: ...
    @property
    def evidence(self) -> DataFrame: ...
    @property
    def functions(self) -> DataFrame: ...
    @property
    def parameters(self) -> DataFrame: ...
    @property
    def references(self) -> DataFrame: ...
    @property
    def tensor_roles(self) -> DataFrame: ...
    def frames(self) -> dict[str, DataFrame]: ...

class CallTables:
    def frames(self) -> dict[str, DataFrame]: ...

class ClassTables:
    @property
    def class_decorators(self) -> DataFrame: ...
    @property
    def class_keywords(self) -> DataFrame: ...
    @property
    def classes(self) -> DataFrame: ...
    @property
    def coupled_group_suffixes(self) -> DataFrame: ...
    @property
    def coupled_groups(self) -> DataFrame: ...
    @property
    def direct_bases(self) -> DataFrame: ...
    @property
    def direct_subclasses(self) -> DataFrame: ...
    @property
    def evidence(self) -> DataFrame: ...
    @property
    def facts(self) -> DataFrame: ...
    @property
    def importing_modules(self) -> DataFrame: ...
    @property
    def method_decorators(self) -> DataFrame: ...
    @property
    def methods(self) -> DataFrame: ...
    @property
    def model_files(self) -> DataFrame: ...
    @property
    def owner_qualified_calls(self) -> DataFrame: ...
    @property
    def projection_attributes(self) -> DataFrame: ...
    @property
    def projection_output_keys(self) -> DataFrame: ...
    @property
    def projections(self) -> DataFrame: ...
    def frames(self) -> dict[str, DataFrame]: ...

class ImportBindingTables:
    @property
    def evidence(self) -> DataFrame: ...
    @property
    def facts(self) -> DataFrame: ...
    @property
    def nodes(self) -> DataFrame: ...
    def frames(self) -> dict[str, DataFrame]: ...

class SyntaxTables:
    @property
    def children(self) -> DataFrame: ...
    @property
    def facts(self) -> DataFrame: ...
    @property
    def nodes(self) -> DataFrame: ...
    def frames(self) -> dict[str, DataFrame]: ...

class GenericTables:
    @property
    def facts(self) -> DataFrame: ...
    @property
    def records(self) -> DataFrame: ...
    @property
    def values(self) -> DataFrame: ...
    def frames(self) -> dict[str, DataFrame]: ...

class GlinerClassifier:
    def __init__(self, model_dir: Path | str) -> None: ...
    def classify(
        self,
        texts: Sequence[str],
        task: str,
        *,
        labels: str,
        batch_size: int,
    ) -> str: ...

class SessionStats:
    @property
    def byte_count(self) -> int: ...
    @property
    def discovery_nanoseconds(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def extraction_nanoseconds(self) -> int: ...
    @property
    def fact_count(self) -> int: ...
    @property
    def file_count(self) -> int: ...
    @property
    def graph_nanoseconds(self) -> int: ...
    @property
    def node_count(self) -> int: ...
    @property
    def parse_failure_count(self) -> int: ...
    @property
    def repository_fingerprint(self) -> str: ...

class AnalysisSession:
    def __init__(
        self,
        root: Path | str,
        typed_families: Sequence[str],
        *,
        python_standard_library: Sequence[str],
        suffixes: Sequence[str] | None = None,
        generic_schemas: dict[str, str] | None = None,
    ) -> None: ...
    def call_tables(self) -> CallTables: ...
    def class_tables(self) -> ClassTables: ...
    def function_tables(self) -> FunctionTables: ...
    def import_binding_tables(self) -> ImportBindingTables: ...
    def next_table_marker(self) -> str | None: ...
    def stats(self) -> SessionStats: ...
    def syntax_tables(self) -> SyntaxTables: ...
    def table(self, family: str) -> GenericTables: ...

def fact_tables(facts: str, *, schema: str) -> GenericTables: ...
