from collections.abc import Sequence

import polars as pl

from ...... import rule
from ......domain.contracts import Unit
from ......facts import AuthorshipSignalFact
from ......query import CountQuery, FindingQuery, RuleQuery
from ......table import Table


@rule("ALL-WRIT0001")
def ai_associated_pattern_count(
    subject: Table[AuthorshipSignalFact], *, providers: Sequence[str] = ()
) -> CountQuery:
    """Count exact AI-associated style patterns reported by external analyzers.

    Definition
    ----------
    Read provider-neutral evidence generated by tools such as Vale AI Tells or Pangram.
    Count every selected pattern occurrence without combining phrase likelihood multiples.
    A provider baseline is retained as a separate measurement because observed count,
    expected count, and authorship probability are different quantities.

    Evidence
    --------
    Each finding preserves the provider, provider version, external rule, matched text, source
    range, and any provider-reported relative likelihood. The configured provider filter is
    case-insensitive. An empty filter includes every provider. The value is the number of selected
    pattern occurrences across every eligible segment.

    Exceptions
    ----------
    A pattern can be intentional, required terminology, quoted text, or ordinary prose in another
    domain or language. This rule reports selected house-style evidence and never claims that a
    person or model authored the text. `providers` selects which analyzers count, matched without
    regard to case, and an empty selection includes every provider the evidence holds. Context
    remains the deciding evidence.

    Examples
    --------
    A document with twenty Pangram evidence instances returns `20`. If Pangram reports an
    expected baseline near four, the baseline stays a separate finding rather than being
    converted into an AI probability. A Vale alert for `At its core` contributes one count.

    References
    ----------
    Cites "Pangram documentation", How our AI detector works
    https://www.pangram.com/research/how-it-works
    Cites "Vale AI Tells"
    https://github.com/tbhb/vale-ai-tells
    Cites "Monitoring AI-Modified Content at Scale"
    https://arxiv.org/abs/2403.07183
    """
    relations = subject
    selected = relations.records("matches").filter(pl.col("is_eligible"))
    if providers:
        selected = selected.filter(
            pl.col("provider").str.to_lowercase().is_in([name.lower() for name in providers])
        )
    frame = relations.counted(selected)
    findings = selected.with_columns(
        pl.col("span.path").alias("path"),
        pl.col("span.start_line").alias("start_line"),
        pl.col("span.start_column").alias("start_column"),
        pl.col("span.end_line").alias("end_line"),
        pl.col("span.end_column").alias("end_column"),
    )
    return RuleQuery.integer(
        frame,
        pl.col("value"),
        findings=FindingQuery.build(
            findings,
            pl.concat_str(
                pl.lit("external analyzer `"),
                pl.col("provider"),
                pl.lit("` reported `"),
                pl.col("matched_text"),
                pl.lit("`"),
            ),
            (("ai associated pattern count", pl.lit(1.0), Unit.COUNT),),
            finding_order=pl.col("ordinal"),
            evidence=pl.concat_list(
                pl.concat_str(
                    pl.col("provider"),
                    pl.lit(" "),
                    pl.col("provider_version"),
                    pl.lit(" "),
                    pl.col("rule"),
                ).str.strip_chars()
            ),
        ),
    )
